name: Add Front Matter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  add-front-matter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Process Documents
        id: process
        run: |
          # 初始化计数器
          declare -i total=0 processed=0 failed=0
          
          process_file() {
            local file="$1"
            # 跳过已有front matter的文件
            if sed -n '1{/^---$/h}; /^---$/{x;p;q}; H' "$file" | grep -q "^---$"; then
              echo "[INFO] 跳过 $file: 已存在 front matter"
              return 0
            fi
            
            # 获取文件信息
            local title=$(basename "$file" .md)
            local date=$(TZ='Asia/Shanghai' date -d "$(git log -1 --format=%aI -- "$file" 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%SZ)" +%Y-%m-%dT%H:%M:%S+08:00)
            local category=$(dirname "$file" | sed 's|^./||')
            
            # 生成front matter
            sed -i "1i---\ntitle: \"$title\"\ndate: $date\ncategories: [\"$category\"]\ntype: \"post\"\n---\n" "$file" && 
            echo "[SUCCESS] 已添加 front matter 到 $file" && return 0
            
            echo "[ERROR] 更新文件失败: $file"
            return 1
          }
          
          # 处理所有markdown文件
          while IFS= read -r file; do
            ((total++))
            process_file "$file" && ((processed++)) || ((failed++))
          done < <(find . -type f -name "*.md" ! -name "README.md")
          
          # 输出结果
          echo "处理结果: 总计 $total, 成功 $processed, 失败 $failed"
          echo "processed=$processed" >> "$GITHUB_OUTPUT"
          echo "failed=$failed" >> "$GITHUB_OUTPUT"

      - name: Commit changes
        if: steps.process.outputs.processed > 0
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "chore: add front matter [skip ci]" || exit 0
          git push
