name: Deploy Hugo site to Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # UTC 每天2点
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      CUSTOM_DOMAIN: ${{ github.event.repository.pages.cname }}
    
    steps:
      # 1. 检出代码（需要完整提交历史）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # 关键修改：获取完整提交历史

      # 2. 设置 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 3. 配置 GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 4. 处理文档并生成 front matter
      - name: Process Markdown files
        run: |
          generate_front_matter() {
            local file="$1"
            local title=$(basename "$file" .md)
            
            # 获取首次提交时间（ISO 8601 格式）
            local first_commit_date=$(git log --reverse --pretty=format:%ad --date=iso-strict -- "$file" | head -1)
            
            # 处理分类路径（去掉开头的./）
            local category=$(dirname "$file" | sed 's|^\./||')

            # 保留已有 front matter
            if sed -n '1{/^---$/h}; /^---$/{x;p;q}; H' "$file" | grep -q "^---$"; then
              mkdir -p "content/$category"
              cp "$file" "content/$category/$title.md"
              return
            fi

            # 生成新 front matter
            {
              echo "---"
              echo "title: \"$title\""
              echo "date: $first_commit_date"
              echo "categories: [\"$category\"]"
              echo "type: \"post\""
              echo "---"
              cat "$file"
            } > "content/$category/$title.md"
          }

          # 遍历所有 md 文件（排除 README.md 且保留目录结构）
          find . -type f -name "*.md" ! -name "README.md" | while read fullpath; do
            # 统一处理路径格式（去掉开头的./）
            filepath=$(echo "$fullpath" | sed 's|^\./||')
            generate_front_matter "$filepath"
          done

      # 5. 获取自定义域名
      - name: Retrieve custom domain
        id: fetch-domain
        run: |
          customDomain=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pages \
          | jq -r '.cname // ""')
          echo "CUSTOM_DOMAIN=$customDomain" >> $GITHUB_ENV

      # 6. 创建并写入 Hugo 配置
      - name: Configure Hugo
        run: |
          if [ -n "$CUSTOM_DOMAIN" ]; then
            domain="$CUSTOM_DOMAIN"
          else
            owner="${GITHUB_REPOSITORY_OWNER}"
            repo="$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
            domain="$owner.github.io/$repo"
          fi

          cat > config.toml << EOL
          baseURL = "https://$domain"
          languageCode = "zh-cn"
          title = "${{ github.repository_owner }}'s Space"
          theme = "PaperMod"

          [params]
            mainSections = ["post"]
            defaultTheme = "auto"
            ShowReadingTime = true
            ShowShareButtons = false
            ShowPostNavLinks = true
            ShowBreadCrumbs = true
            ShowCodeCopyButtons = true
            ShowToc = true

            [params.homeInfoParams]
              Title = "欢迎来到 ${{ github.repository_owner }} 的文档站"
              Content = "在喧嚣时代中静心思考，用文字传递理性与希望。"

            [[params.socialIcons]]
              name = "github"
              url = "https://github.com/${{ github.repository_owner }}"

          [outputs]
            home = ["HTML", "RSS", "JSON"]

          [taxonomies]
            category = "categories"
            tag = "tags"

          [menu]
            main = [
              {identifier = "archives", name = "Archives", url = "/archives/", weight = 10},
              {identifier = "categories", name = "Categories", url = "/categories/", weight = 20},
              {identifier = "search", name = "Search", url = "/search/", weight = 30},
              {identifier = "tags", name = "Tags", url = "/tags/", weight = 40}
            ]
          EOL

          # 创建必要页面
          mkdir -p content
          cat > content/search.md << EOL
          ---
          title: "Search"
          layout: "search"
          summary: "search"
          placeholder: "搜索文章..."
          ---
          EOL

          cat > content/archives.md << EOL
          ---
          title: "Archives"
          layout: "archives"
          url: "/archives/"
          summary: "archives"
          ---
          EOL

      # 7. Hugo 构建
      - name: Build site
        run: hugo --minify

      # 8. 上传构建产物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      # 9. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
